version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql-wac
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=whatsapp_clone
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 2112:3306
    networks:
      - whatsapp_clone
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak-wac
    ports:
      - 9090:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - whatsapp_clone
    command: "start-dev"
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  whatsapp_clone:
    driver: bridge